### ISSUE TITLE
the current desktop/apps page is reported, although it shouldn't

### ISSUE THREAD

**Issue by pldimitrov** [pilot51/voicenotify#23]
I unticked the following apps:

Active applications
Android System
com.samsung.InputEventApp
System UI
SystemInfo
SASlideShow
Samsung Apps

And only ticked the device states:

Screen Off
Headset On

The app reports the current desktop/apps page "Page X of Y" even though the screen is on and the headset is off.

Model number: GT-I9100
Android version: 4.1.2
Baseband version: I9100XXLS8
Kernel version: 3.0.31-899555 dpi@DELL228 #3 SMP PREEMPT Thu Jan 31 14:48:54 KST 2013
Build number: JZO54K.I9100XWLSD

**Comment by pilot51** [comment]
I'm confident this was fixed in 682bbb7 by reading notifications through Notification Listener Service instead of Accessibility Service. As a side effect of this change, VN no longer supports versions of Android prior to 4.3. Of course, if the issue only existed prior to 4.3, this isn't really a fix and anyone still affected should upgrade.
