### ISSUE TITLE
Cannot read content from Fibaro HC app

### ISSUE THREAD

**Issue by kimbo1st** [pilot51/voicenotify#50]
Hi,

The app works great, but the push messages which I receive from Fibaro HomeCenter app... it says the app name but not the content of t.

Is this a big or maybe an enhancement?

thanks

**Comment by pilot51** [comment]
This is an enhancement and a duplicate of Issue #5.

Long story short, I've been having serious motivation issues in regard to my apps since I got my job over 3 years ago. So, sorry for the long delay in anything getting done. The fact that I'm finally here in the issue tracker is a step in the right direction.
