### ISSUE TITLE
Doesn't work on Marshmallow and up

### ISSUE THREAD

**Issue by edickey6** [pilot51/voicenotify#55]
The app needs to request notification access on Marshmallow and up but since it doesn't request it, it simply doesn't work

**Comment by clijunky** [comment]
I believe this is resolved. Works for me, requested access

**Comment by edickey6** [comment]
clijunky, I can't remember exactly what the issue I had and hard of back the but my current issue is that is not able to read full notification. Probably related too the other "Fully read Jellybean extended notifications #5" issue which is still open

**Comment by pilot51** [comment]
I couldn't reproduce in 7.x or 8.0 to determine what exactly this issue was, though I have received a few other reports about it not working in recent Android versions.

I'm confident that reading notifications through Notification Listener Service instead of Accessibility Service likely fixed it in 682bbb7.
