### ISSUE TITLE
Development setup instructions

### ISSUE THREAD

**Issue by haxwithaxe** [pilot51/voicenotify#59]
I'd like to work on some improvements, but I'm having trouble getting this into Android Studio without mangling it. Any pointers on doing that or on replicating your dev environment? I'll do some documentation as my first pull request ;)

**Comment by pilot51** [comment]
Thanks for the heads-up and your willingness to contribute.

I was just using [GitHub's Android gitignore](https://github.com/github/gitignore/blob/master/Android.gitignore) and didn't bother to test it by importing into a new project. I did just now. As far as I've been able to find, the .iml files should not be included in the repository because they could be machine-specific (mainly project directory name) and Android Studio can easily recreate the files.

The two issues I ran into when creating a new project from Git were the missing .iml files and that it wanted me to select the Android SDK (even though it's already configured) when I tried running the app. I found that you can simply go to Tools > Android > Sync Project with Gradle Files and it will create the proper .iml files and fix the SDK issue. It should build and run fine after that. It doesn't matter if you remove the modules in the prompt, though you may see an error for the VoiceNotify module file missing every time you open the project if your project directory is named differently, in which case you'll want to remove the module from the project.

Hopefully that helps. If not, please provide more detail of the issue.

**Comment by haxwithaxe** [comment]
Works for me.
