### ISSUE TITLE
Empty messages spoken as "dot dot"

### ISSUE THREAD

**Issue by pilot51** [pilot51/voicenotify#63]
Reported via email:
> Hello and thank you for making a great app. Since u recently updated, blank messages in the log are continuing to announced as, "dot dot" on note 4. I have to ignore the entire app when ever any one app sends a blank notification. Thank u

My response:
> I have not been able to reproduce. I suspect it may be caused by the periods in the TTS Message option and Samsung's TTS engine not keeping isolated periods silent the same way Google or Pico TTS does. Assuming that's the cause, I should have it fixed in the next update.
> 
> Two workarounds to try:
> 1. Remove the periods in the Text-To-Speech > TTS Message setting.
> 2. Switch to another TTS engine such as Google TTS.
> 
> Please report back whether either of those work so I know if my assumption is correct. Unfortunately, Samsung TTS isn't available for any of my devices to test.

**Comment by rakolambski** [comment]
Just so you don't think it's only Samsung, I see (hear) this behavior on Voice Notify  v1.1.3 whenever I start playing an e-book in Audible player.  I start playing, and Voice Notify speaks "dot dot".  I'm using Google Text-to-speech Engine, Android-8.1.0 / OxygenOS version 5.1.4 on OnePlus-5T, and I'm a beta VN user.

For the record, I'm using "#c. #m." as the "TTS Message", based on the "Default" listed, with the ""#a." part removed to avoid speaking the App title.

Just tested, and the periods listed in the the "TTS Message" format are what's being spoken.  I'm not sure what the "." (or the ":" in the "Old default" string of "#a: #t") does - I would assume a "spoken delay" perhaps?

Changing "TTS Message" to "#c #m" eliminates the "dot dot" from speaking, but Audible will still pause while <apparently nothing> is spoken, then resume.  I'm thinking that if there's actually nothing to speak, VN probably shouldn't send the "Pause/dim media" request, since there's nothing to hear.
[AER]
