### ISSUE TITLE
NP Service Shown Disable but Still Running 

### ISSUE THREAD

**Issue by piweihwt** [pilot51/voicenotify#7]
Running on 4.0.4.

And when I restart my phone, NP Service can't work.
Why?

**Comment by pilot51** [comment]
While I was never able to reproduce, this was very likely fixed in 682bbb7 by reading notifications through Notification Listener Service instead of Accessibility Service. That would get rid of all the weird issues specifically with accessibility services.

The VN service still needs to be manually enabled in Android settings after install, now in Notification Access instead of Accessibility. The top option in VN will take you to the correct settings screen.
