### ISSUE TITLE
Disappeared from Google Play Store

### ISSUE THREAD

**Issue by sketch242** [pilot51/voicenotify#77]
I just got a new phone and went to install Voice Notify from the play store, but it's no longer there. What happened?

**Comment by famewolf** [comment]
It's on fdroid.org.   No idea why the move though.

**Comment by sketch242** [comment]
Yep, I installed it from there.  Seems funny that the documentation still references the play store, though.

**Comment by pilot51** [comment]
Sorry for leaving this sit for so long. Google removed it in Jan 2019 because the donation option used Google Wallet and PayPal instead of the Google Play payment system. Since I've switched to keeping my phone on silent/vibrate and no longer use Voice Notify personally, and I'm a full-time developer with other interests that I want to spend my free time on, I just haven't had the motivation to work on it, let alone reply to issues and emails (horrible of me).

I did not publish on F-Droid. I believe they automatically pulled it from GitHub. F-Droid is a good service, though I usually point people to the releases on GitHub when anyone asks where to download it since the APK is signed with the same key used in the Play Store, preserving settings when updated if the app was originally installed from Play Store or GitHub. F-Droid builds it from source with their own key.

I recently found that a company copied Voice Notify and published on the Play Store, only removing or replacing references to me, contributors, and the original project to give themselves (the company and 3 people who supposedly work for them) credit for developing it. I'm fine with people copying it as long as proper credit is given, or at least not stolen as it was in this case.
I emailed them in November to ask that they either provide proper credit for the original work or make theirs open source with the full commit history, which they replied 8 minutes later that they would do, but as of now they've done nothing about it.
While they originally published it in 2020 with the same name and icon, there were reviews from users who said they've been using it for up to 15 years (though VN was originally released in 2011), and the company replied "Thanks" to take the credit.
Apparently that was the motivation I needed to do something because I really don't like the idea of people mistaking an unsupported copy with stolen credit for the true original.

I am currently working on updating the project to current standards, including some cool stuff I've learned over the years like Kotlin, and should have it republished Soon™ without the donate option. Since the project has other contributors, I don't feel right taking donations anyway.

**Comment by pilot51** [comment]
Sorry for the 8 month delay, long story, but I'm back at it again.

I tried republishing with v1.2.0 last weekend and it was rejected after 6 days in review for not having a privacy policy in the app, which is apparently a new Google policy I didn't know about. I resolved it and started rollout a couple hours ago. Hopefully they approve it this time. I'll close this issue once it goes live.

**Comment by pilot51** [comment]
It's back on the Play Store as of Wednesday!
