### ISSUE TITLE
Voice notify turns itself on by itself

### ISSUE THREAD

**Issue by drathier** [pilot51/voicenotify#96]
I haven't figured out when it happens yet, but voice notify definitely turns itself on by itself every once in a while. It wasn't a problem back when the permission was handled by android, which makes sense, but it has been since the "suspended" feature was added.

**Comment by pilot51** [comment]
I could use more information to reproduce. Could you give a ballpark for how often "every once in a while" is? If you could figure out what triggers it, that would be a huge help.

The suspend feature was added in 2013 with commit 46cd6e1, so I doubt that has anything to do with it.

Do you mean it wasn't a problem when permissions were requested at install instead of runtime? That was done in early 2022 with commit 870b1a3 because the old way was deprecated. A whole bunch of other behind-the-scenes changes happened with that release ([v1.2.0](https://github.com/pilot51/voicenotify/releases/tag/v1.2.0)), so I'm not surprised if the regression happened somewhere in that mess.
